### ISSUE TITLE
Two bugs in v2.0 of the extension

### ISSUE THREAD

**Issue by InvisibleManX** [oslego/better-twitter#11]
Two issues are present on Waterfox Current (on a Windows PC), which is a fork from Firefox 68. 
(And there are no issues with the disabled "Better Twitter".)

As an example I will use this profile's timeline: 
[https://twitter.com/tweetsauce](https://twitter.com/tweetsauce)

**There are two bugs, when scrolling through the "Latest Tweets" timeline or any other person's profile timeline:** 

**1.** Instead of videos (and their previews) there are big empty spaces (in both actual tweets and retweets as well):  

[https://i.imgur.com/ZkahBsy.png](https://i.imgur.com/ZkahBsy.png)

If a specific tweet is opened in a separate browser tab, the video is shown and plays just fine again.

**2.** "Who to follow" in people's timeline doesn't show any suggestions, but there's a huge white space left in its place. 
(That section isn't immediately shown, so to see it you'd need to scroll down for several tweets first).: 

[https://i.imgur.com/wqJZQ9O.png](https://i.imgur.com/wqJZQ9O.png)

Though, if this specific issue is the only way to hide the Who to follow suggestions, then it's an acceptable compromise. 

However, the first issue with videos and their previews not being displayed unless opened in separate tabs is definitely something that needs to be resolved. Otherwise the extension isn't really usable this way.

**Comment by oslego** [comment]
Thanks for reporting, @InvisibleManX!

The issues have been fixed in version 2.0.1, now available: https://addons.mozilla.org/en-US/firefox/addon/better-twitter-extension/

If you still have a previous version installed, please go to to `about:addons` in your browser, click the gear icon and select "Check for Updates".

**Comment by InvisibleManX** [comment]
Thank you! Everything works great now! :)
