### ISSUE TITLE
Hide "Who to follow" causes people to be not found when searching

### ISSUE THREAD

**Issue by grahamperrin** [oslego/better-twitter#12]
### Step

1. https://twitter.com/search?q=Melissa%20floyd&f=user

### Expected

2. a list of matching people

### Actual result

2. a list flickers then disappears

![image](https://user-images.githubusercontent.com/192271/89568713-9e504a00-d81b-11ea-86d2-ef00d3982792.png)

**Comment by oslego** [comment]
Indeed, this is a bug. Thanks for reporting!
