### ISSUE TITLE
Support Firefox for Android

### ISSUE THREAD

**Issue by davidmegginson** [oslego/better-twitter#15]
I'd love to be able to use this extension in Firefox for Android (I use that instead of the Twitter app). Would it be a major modification to make that work?

**Comment by oslego** [comment]
[Firefox for Android is changing](https://www.ghacks.net/2020/08/07/three-reasons-not-to-upgrade-to-the-new-firefox-for-android-browser-right-now/) in a way that restricts open distribution of web extensions. In the beginning, just a subset of vetted extensions will be available. Over time, this list may expand. Until then, third party extensions like Better Twitter will probably not work on the new Firefox for Android.

**Comment by davidmegginson** [comment]
Yes, I just discovered that after I left this issue, when my FF updated on Android. I don't know what's going on behind the scenes, but maybe it's time to fork Firefox if some of the companies funding the Mozilla foundation are pushing them to make it harder to hide ads, remove spam posts on Twitter, etc.
