### ISSUE TITLE
Mighty annoyed by new Firefox for Android.

### ISSUE THREAD

**Issue by Scott71oldguy** [oslego/better-twitter#18]
Why is this radically different interface dropped on me (us)?

You've left me dead in the water. No toolbar (I can't find how to bring it up, anyway). Can't open a new tab. Can't do much. Had to go to a PC  to do this.

This is harsh, folks. Complex systems that work EVOLVE from simple systems that work.

Throw me a rope, please.

79.0.5 (Build 2015758619)   I see that this must have come down on 8/18, but it just hit me (hard) overnight 8/30..

**Comment by oslego** [comment]
@Scott71oldguy, You left this comment on the repository for a web extension that happens to work in Firefox.

The place where you're looking to vent your frustration is probably the [Firefox for Android entry on the Google Play Store](https://play.google.com/store/apps/details?id=org.mozilla.firefox&hl=en).
