### ISSUE TITLE
Hide tweets with/without certain content

### ISSUE THREAD

**Issue by ImJezze** [oslego/better-twitter#33]
I have a request for a more complex feature that can hide tweets based on their content.

For example, I don't want to see tweets that only contain text. Because I mostly follow artists and want to see the art they share, but I don't want to see simple tweets that only contain text.

Since other people may prefer different criteria to hide tweets, I'd like to suggest an input field where you can enter a (regular) expression. If the expression matches, the tweet will be hidden. It would probably also be useful to be able to negate this filter.

The filter should only apply to the home feed. The filter should not apply when you open a thread to read the replies. (or as option to define where the filter should be applied)

**Comment by oslego** [comment]
@ImJezze Sounds like a useful idea, but it's not trivial to implement. 

The regular expression aspect is something beyond most people's capabilities. Ideally, there would be a subset of things to filter by (only images, only video, only emoji, only text content, etc.), exposed as filters to make it more accessible to people. And a free-form RegEx field for power users, if done well.

It's certainly a clever idea, but perhaps something better suited for a standalone extension. The guiding principle behind Better Twitter is to remove distractions or addictive features. What you're proposing branches into curation, which sounds useful, but beyond the scope of this extension.

Feel free to use Better Twitter code as an inspiration if you want to build it yourself.
