### ISSUE TITLE
Unable to view followers/following lists

### ISSUE THREAD

**Issue by reederda** [oslego/better-twitter#6]
When this extension is enabled, https://twitter.com/(user)/following and https://twitter.com/(user)/followers constantly flash and reload.

**Comment by oslego** [comment]
Argh! This is a regression from 5f7fafd2ecad8aaf64280b11802ae15ebf119df0 from version 1.4.3
I'll have a fix or a rollback shortly.

**Comment by oslego** [comment]
Thank you for reporting this! The issue has been fixed in an updated version 1.4.4 and published to the [Firefox Add-ons store](https://addons.mozilla.org/en-US/firefox/addon/better-twitter-extension/).
