### ISSUE TITLE
Hide ads/remove prompt from blocking ad accounts

### ISSUE THREAD

**Issue by Derahex** [oslego/better-twitter#66]
Ads appear frequently with checkmarked accounts, and blocking a checkmarked account prompts user to upgrade every single time.

![1](https://github.com/oslego/better-twitter/assets/58238159/e9cf2d26-c651-41c1-8f87-19d63654d886)

![2](https://github.com/oslego/better-twitter/assets/58238159/5939384d-a759-44ef-ad04-82c9a04a0ebd)

**Comment by oslego** [comment]
Fixed hiding promoted tweets in https://github.com/oslego/better-twitter/commit/cb9972d758db4e342469588da92a24378f171eb7
Available in version 2.1.3

**Comment by oslego** [comment]
Fixed hiding promoted tweets in https://github.com/oslego/better-twitter/commit/cb9972d758db4e342469588da92a24378f171eb7
Available in version 2.1.3
