### ISSUE TITLE
Who To Follow isn't hidden when viewing tweets from people's profiles

### ISSUE THREAD

**Issue by InvisibleManX** [oslego/better-twitter#7]
The issue is present on Waterfox Current (on a Windows PC), which is a fork from Firefox 68, from what I undestand. (UPDATE: CyberChaosCrew confirmed this issue to be present in the latest Firefox as well).

The extension seems to perform all its functions properly, except hiding "Who To Follow", when viewing tweets after going to any person's profile. 

The issue is present in both "Tweets" and "Tweets & replies" sections. 

The "Who to Follow" part appears if the page with tweets is scrolled down a bit. Scroll down a dozen or two of tweets and it's always there! No matter what settings are chosen in the extension's options.

I don't mean the things on the right side, which are hidden just fine. 

I mean, while viewing not from the Home feed page, but from any person's profile, a section of "Who to Follow" appears right among the actual tweets, while scrolling down through them.

**Comment by CyberChaosCrew** [comment]
I have this exact same issue on Firefox 77.0.1 (64-bit) (latest version), would be nice if you could fix it.

All the options are working except "Hide "Who to follow"", regardless of it being active or not I always get the "Who to follow" popup on the Tweets/Tweets & Replies timeline.

**Comment by kingwolfen0** [comment]
Same here. Firefox 77.0.1 (64-bit), Windows 10 version 1909.

**Comment by oslego** [comment]
Hi folks! Thanks for logging the issue!

It is addressed in [v2.0 currently in beta](https://github.com/oslego/better-twitter/releases/tag/v2.0-beta). If you can, I would appreciate your help beta testing that version.

Twitter doesn't make it easy to hide elements on its website. Hiding "Who to follow" in a user's timeline is particularly tricky.
Version 2.0 of the extension uses a new approach to identify elements. I'm trialing this on my own account to look for any side-effects.

If nothing obvious is broken, I intend to push v2.0 to the Firefox and Chrome extension stores within 7 days.

**Comment by oslego** [comment]
29 days later :) I released v2.0 on the Mozilla Add-ons store and Chrome Web Store
