### ISSUE TITLE
Promoted Tweets appear back on v2.1.3

### ISSUE THREAD

**Issue by ryanj2323** [oslego/better-twitter#72]
Cannot hide promoted tweets on v2.1.3, Firefox 125.0.3 (Ubuntu Linux)

**Comment by oslego** [comment]
Tested v2.1.3 in Firefox and it still works. If Twitter is A/B testing how they mark promoted ads, I'm not getting the change.
Closing until there's an actionable change.

![Screenshot 2024-05-25 at 13 37 14](https://github.com/oslego/better-twitter/assets/63899/9be47662-01ec-495b-a0f1-6d7edb8287af)
![Screenshot 2024-05-25 at 13 37 16](https://github.com/oslego/better-twitter/assets/63899/c3675615-7933-4ffa-9ae4-1ecf7c4552fc)

**Comment by ryanj2323** [comment]
Thank you for review,

FYI)
I imported this Chrome Extension to Firefox, and it works.

https://github.com/ryanckulp/twitter_ad_blocker
