### ISSUE TITLE
"Explore" section still shows up when logged out.

### ISSUE THREAD

**Issue by kingwolfen0** [oslego/better-twitter#8]
Not sure if it's intentional or not, but the "Explore" section in the main page when logged out still shows up, along with trends at the bottom. Sorry if it is intentional, I guess then it can be considered a feature request?

Using Firefox 77.0.1 (64-bit) on Windows 10 version 1909.

**Comment by oslego** [comment]
"Better Twitter" explicitly handles the experience while logged-in.

The Twitter interface and structure changes often and breaks features. Unfortunately, it's disproportionately too much effort to handle and maintain the particular cases while logged-out.
