### ISSUE TITLE
"What's happening" section still shows up.

### ISSUE THREAD

**Issue by kingwolfen0** [oslego/better-twitter#9]
Not sure if it's intentional or not, but when logged in, the "What's happening" section still shows up on the right. If it is it could be considered a feature request.

Using Firefox 77.0.1 (64-bit), Windows 10 version 1909.

**Comment by oslego** [comment]
@kingwolfen0 Can you please try again with the latest version of the extension, v2.0

If it's still happening, can you please leave a link or describe where in the website this panel shows up?

**Comment by oslego** [comment]
Assuming this is addressed by v2.0
If not, please reopen the issue and post a screenshot.
